FROM alpine:latest as certs
RUN apk --update add ca-certificates

FROM scratch
MAINTAINER Sovereign Development "dev@lgcorzo.com"
EXPOSE 8080

COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY sidekick /bin/sidekick

ENTRYPOINT ["/bin/sidekick"]
