name: VulnCheck
on:
  pull_request:
    branches:
    - master
    - main
  push:
    branches:
    - master
    - main
jobs:
  vulncheck:
    name: Analysis
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.24.0]
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Run govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: ${{ matrix.go-version }}
          check-package: './...'
